version: "3.9"

services:
  redis-a:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  redis-b:
    image: redis:7-alpine
    ports:
      - "6381:6379"

  # redgate:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: ["--config", "/app/config.yaml"]
  #   volumes:
  #     - ./config.example.yaml:/app/config.yaml:ro
  #   ports:
  #     - "6380:6380"
  #     - "9109:9109"
  #     - "16380:16380"
  #   depends_on:
  #     - redis-a
  #     - redis-b
